name: Update Weather

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-weather:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install
      - run: node weather.js
        env:
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
      - run: |
          git config user.name "NKKNix"
          git config user.email "supawit.thongrueng@gmail.com"
          git add weather.svg
          git diff --cached --quiet && echo "No changes to commit" || git commit -m "Update weather"
          git push
